// Auto-generated by scripts/extract-manual.mjs — do not edit
export const MANUAL_IMAGES = [
  {
    "filename": "owner-manual-page-001.png",
    "url": "/manual-images/owner-manual-page-001.png",
    "source": "Owner's Manual",
    "page": 1,
    "label": "Owner's Manual — Page 1",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-002.png",
    "url": "/manual-images/owner-manual-page-002.png",
    "source": "Owner's Manual",
    "page": 2,
    "label": "Owner's Manual — Page 2",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-003.png",
    "url": "/manual-images/owner-manual-page-003.png",
    "source": "Owner's Manual",
    "page": 3,
    "label": "Owner's Manual — Page 3",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-004.png",
    "url": "/manual-images/owner-manual-page-004.png",
    "source": "Owner's Manual",
    "page": 4,
    "label": "Owner's Manual — Page 4",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-005.png",
    "url": "/manual-images/owner-manual-page-005.png",
    "source": "Owner's Manual",
    "page": 5,
    "label": "Owner's Manual — Page 5",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-006.png",
    "url": "/manual-images/owner-manual-page-006.png",
    "source": "Owner's Manual",
    "page": 6,
    "label": "Owner's Manual — Page 6",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-007.png",
    "url": "/manual-images/owner-manual-page-007.png",
    "source": "Owner's Manual",
    "page": 7,
    "label": "Owner's Manual — Page 7",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-008.png",
    "url": "/manual-images/owner-manual-page-008.png",
    "source": "Owner's Manual",
    "page": 8,
    "label": "Owner's Manual — Page 8",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-009.png",
    "url": "/manual-images/owner-manual-page-009.png",
    "source": "Owner's Manual",
    "page": 9,
    "label": "Owner's Manual — Page 9",
    "type": "diagram"
  },
  {
    "filename": "owner-manual-page-010.png",
    "url": "/manual-images/owner-manual-page-010.png",
    "source": "Owner's Manual",
    "page": 10,
    "label": "Owner's Manual — Page 10",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-011.png",
    "url": "/manual-images/owner-manual-page-011.png",
    "source": "Owner's Manual",
    "page": 11,
    "label": "Owner's Manual — Page 11",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-012.png",
    "url": "/manual-images/owner-manual-page-012.png",
    "source": "Owner's Manual",
    "page": 12,
    "label": "Owner's Manual — Page 12",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-013.png",
    "url": "/manual-images/owner-manual-page-013.png",
    "source": "Owner's Manual",
    "page": 13,
    "label": "Owner's Manual — Page 13",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-014.png",
    "url": "/manual-images/owner-manual-page-014.png",
    "source": "Owner's Manual",
    "page": 14,
    "label": "Owner's Manual — Page 14",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-015.png",
    "url": "/manual-images/owner-manual-page-015.png",
    "source": "Owner's Manual",
    "page": 15,
    "label": "Owner's Manual — Page 15",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-016.png",
    "url": "/manual-images/owner-manual-page-016.png",
    "source": "Owner's Manual",
    "page": 16,
    "label": "Owner's Manual — Page 16",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-017.png",
    "url": "/manual-images/owner-manual-page-017.png",
    "source": "Owner's Manual",
    "page": 17,
    "label": "Owner's Manual — Page 17",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-018.png",
    "url": "/manual-images/owner-manual-page-018.png",
    "source": "Owner's Manual",
    "page": 18,
    "label": "Owner's Manual — Page 18",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-019.png",
    "url": "/manual-images/owner-manual-page-019.png",
    "source": "Owner's Manual",
    "page": 19,
    "label": "Owner's Manual — Page 19",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-020.png",
    "url": "/manual-images/owner-manual-page-020.png",
    "source": "Owner's Manual",
    "page": 20,
    "label": "Owner's Manual — Page 20",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-021.png",
    "url": "/manual-images/owner-manual-page-021.png",
    "source": "Owner's Manual",
    "page": 21,
    "label": "Owner's Manual — Page 21",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-022.png",
    "url": "/manual-images/owner-manual-page-022.png",
    "source": "Owner's Manual",
    "page": 22,
    "label": "Owner's Manual — Page 22",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-023.png",
    "url": "/manual-images/owner-manual-page-023.png",
    "source": "Owner's Manual",
    "page": 23,
    "label": "Owner's Manual — Page 23",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-024.png",
    "url": "/manual-images/owner-manual-page-024.png",
    "source": "Owner's Manual",
    "page": 24,
    "label": "Owner's Manual — Page 24",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-025.png",
    "url": "/manual-images/owner-manual-page-025.png",
    "source": "Owner's Manual",
    "page": 25,
    "label": "Owner's Manual — Page 25",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-026.png",
    "url": "/manual-images/owner-manual-page-026.png",
    "source": "Owner's Manual",
    "page": 26,
    "label": "Owner's Manual — Page 26",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-027.png",
    "url": "/manual-images/owner-manual-page-027.png",
    "source": "Owner's Manual",
    "page": 27,
    "label": "Owner's Manual — Page 27",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-028.png",
    "url": "/manual-images/owner-manual-page-028.png",
    "source": "Owner's Manual",
    "page": 28,
    "label": "Owner's Manual — Page 28",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-029.png",
    "url": "/manual-images/owner-manual-page-029.png",
    "source": "Owner's Manual",
    "page": 29,
    "label": "Owner's Manual — Page 29",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-030.png",
    "url": "/manual-images/owner-manual-page-030.png",
    "source": "Owner's Manual",
    "page": 30,
    "label": "Owner's Manual — Page 30",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-031.png",
    "url": "/manual-images/owner-manual-page-031.png",
    "source": "Owner's Manual",
    "page": 31,
    "label": "Owner's Manual — Page 31",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-032.png",
    "url": "/manual-images/owner-manual-page-032.png",
    "source": "Owner's Manual",
    "page": 32,
    "label": "Owner's Manual — Page 32",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-033.png",
    "url": "/manual-images/owner-manual-page-033.png",
    "source": "Owner's Manual",
    "page": 33,
    "label": "Owner's Manual — Page 33",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-034.png",
    "url": "/manual-images/owner-manual-page-034.png",
    "source": "Owner's Manual",
    "page": 34,
    "label": "Owner's Manual — Page 34",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-035.png",
    "url": "/manual-images/owner-manual-page-035.png",
    "source": "Owner's Manual",
    "page": 35,
    "label": "Owner's Manual — Page 35",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-036.png",
    "url": "/manual-images/owner-manual-page-036.png",
    "source": "Owner's Manual",
    "page": 36,
    "label": "Owner's Manual — Page 36",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-037.png",
    "url": "/manual-images/owner-manual-page-037.png",
    "source": "Owner's Manual",
    "page": 37,
    "label": "Owner's Manual — Page 37",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-038.png",
    "url": "/manual-images/owner-manual-page-038.png",
    "source": "Owner's Manual",
    "page": 38,
    "label": "Owner's Manual — Page 38",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-039.png",
    "url": "/manual-images/owner-manual-page-039.png",
    "source": "Owner's Manual",
    "page": 39,
    "label": "Owner's Manual — Page 39",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-040.png",
    "url": "/manual-images/owner-manual-page-040.png",
    "source": "Owner's Manual",
    "page": 40,
    "label": "Owner's Manual — Page 40",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-041.png",
    "url": "/manual-images/owner-manual-page-041.png",
    "source": "Owner's Manual",
    "page": 41,
    "label": "Owner's Manual — Page 41",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-042.png",
    "url": "/manual-images/owner-manual-page-042.png",
    "source": "Owner's Manual",
    "page": 42,
    "label": "Owner's Manual — Page 42",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-043.png",
    "url": "/manual-images/owner-manual-page-043.png",
    "source": "Owner's Manual",
    "page": 43,
    "label": "Owner's Manual — Page 43",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-044.png",
    "url": "/manual-images/owner-manual-page-044.png",
    "source": "Owner's Manual",
    "page": 44,
    "label": "Owner's Manual — Page 44",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-045.png",
    "url": "/manual-images/owner-manual-page-045.png",
    "source": "Owner's Manual",
    "page": 45,
    "label": "Owner's Manual — Page 45",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-046.png",
    "url": "/manual-images/owner-manual-page-046.png",
    "source": "Owner's Manual",
    "page": 46,
    "label": "Owner's Manual — Page 46",
    "type": "text"
  },
  {
    "filename": "owner-manual-page-047.png",
    "url": "/manual-images/owner-manual-page-047.png",
    "source": "Owner's Manual",
    "page": 47,
    "label": "Owner's Manual — Page 47",
    "type": "diagram"
  },
  {
    "filename": "owner-manual-page-048.png",
    "url": "/manual-images/owner-manual-page-048.png",
    "source": "Owner's Manual",
    "page": 48,
    "label": "Owner's Manual — Page 48",
    "type": "text"
  },
  {
    "filename": "quick-start-page-001.png",
    "url": "/manual-images/quick-start-page-001.png",
    "source": "Quick Start Guide",
    "page": 1,
    "label": "Quick Start Guide — Page 1",
    "type": "text"
  },
  {
    "filename": "quick-start-page-002.png",
    "url": "/manual-images/quick-start-page-002.png",
    "source": "Quick Start Guide",
    "page": 2,
    "label": "Quick Start Guide — Page 2",
    "type": "diagram"
  },
  {
    "filename": "selection-chart-page-001.png",
    "url": "/manual-images/selection-chart-page-001.png",
    "source": "Process Selection Chart",
    "page": 1,
    "label": "Process Selection Chart — Page 1",
    "type": "diagram"
  }
];
