/**
 * Extracts text and page images from the 3 Vulcan OmniPro 220 PDFs.
 * Run with: node scripts/extract-manual.mjs
 */

import mupdf from "mupdf";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

const FILES_DIR = path.join(ROOT, "files");
const OUTPUT_IMG_DIR = path.join(ROOT, "public", "manual-images");
const OUTPUT_LIB_DIR = path.join(ROOT, "lib");

const PDFS = [
  { filename: "owner-manual.pdf", label: "Owner's Manual", prefix: "owner-manual" },
  { filename: "quick-start-guide.pdf", label: "Quick Start Guide", prefix: "quick-start" },
  { filename: "selection-chart.pdf", label: "Process Selection Chart", prefix: "selection-chart" },
];

// Pages with little text are diagrams (wiring, schematics, parts, control
// panels, assembly drawings); text-heavy pages get quoted verbatim instead.
// 700 captures all unambiguous diagrams while excluding spec tables and
// instruction pages that hover around 1000+ chars.
const DIAGRAM_TEXT_THRESHOLD = 700;

function extractPdf(pdfInfo) {
  const pdfPath = path.join(FILES_DIR, pdfInfo.filename);
  const data = fs.readFileSync(pdfPath);
  const doc = mupdf.Document.openDocument(data, "application/pdf");
  const pageCount = doc.countPages();

  console.log(`  ${pdfInfo.label}: ${pageCount} pages`);

  const allText = [];
  const images = [];

  for (let i = 0; i < pageCount; i++) {
    const page = doc.loadPage(i);

    // Extract text
    const structured = page.toStructuredText("preserve-whitespace");
    const pageText = structured.asText();
    allText.push(`--- ${pdfInfo.label} | Page ${i + 1} ---\n${pageText}`);

    // Render to PNG at 1.5x scale
    const matrix = mupdf.Matrix.scale(1.5, 1.5);
    const pixmap = page.toPixmap(matrix, mupdf.ColorSpace.DeviceRGB, false, true);
    const png = pixmap.asPNG();

    const imgFilename = `${pdfInfo.prefix}-page-${String(i + 1).padStart(3, "0")}.png`;
    const imgPath = path.join(OUTPUT_IMG_DIR, imgFilename);
    fs.writeFileSync(imgPath, png);

    const dense = pageText.replace(/\s+/g, "").length;
    const type = dense <= DIAGRAM_TEXT_THRESHOLD ? "diagram" : "text";

    images.push({
      filename: imgFilename,
      url: `/manual-images/${imgFilename}`,
      source: pdfInfo.label,
      page: i + 1,
      label: `${pdfInfo.label} — Page ${i + 1}`,
      type,
    });

    process.stdout.write(`\r  Page ${i + 1}/${pageCount} rendered   `);
  }

  console.log("");
  return { text: allText.join("\n\n"), images };
}

function main() {
  console.log("Extracting Vulcan OmniPro 220 manuals...\n");

  fs.mkdirSync(OUTPUT_IMG_DIR, { recursive: true });
  fs.mkdirSync(OUTPUT_LIB_DIR, { recursive: true });

  const allText = [];
  const allImages = [];

  for (const pdf of PDFS) {
    console.log(`Processing: ${pdf.label}`);
    const { text, images } = extractPdf(pdf);
    allText.push(text);
    allImages.push(...images);
  }

  // Write lib/manual-content.js (plain JS for easy import)
  const contentJs = `// Auto-generated by scripts/extract-manual.mjs — do not edit
export const MANUAL_TEXT = ${JSON.stringify(allText.join("\n\n===\n\n"))};
`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-content.js"), contentJs);

  // Also write a TypeScript declaration file
  const contentDts = `export declare const MANUAL_TEXT: string;\n`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-content.d.ts"), contentDts);

  console.log("Wrote lib/manual-content.js");

  // Write lib/manual-images.js
  const imagesJs = `// Auto-generated by scripts/extract-manual.mjs — do not edit
export const MANUAL_IMAGES = ${JSON.stringify(allImages, null, 2)};
`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-images.js"), imagesJs);

  const imagesDts = `export interface ManualImage {
  filename: string;
  url: string;
  source: string;
  page: number;
  label: string;
  type: "diagram" | "text";
}
export declare const MANUAL_IMAGES: ManualImage[];\n`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-images.d.ts"), imagesDts);

  console.log("Wrote lib/manual-images.js");
  console.log(`\nDone! ${allImages.length} page images across ${PDFS.length} PDFs.`);
}

main();
