/**
 * Extracts text and page images from the 3 Vulcan OmniPro 220 PDFs.
 * Outputs:
 *   - public/manual-images/*.png  (one per page)
 *   - lib/manual-content.ts       (full extracted text)
 *   - lib/manual-images.ts        (image metadata)
 *
 * Run with: npm run extract-manual
 */

import mupdf from "mupdf";
import fs from "fs";
import path from "path";

const FILES_DIR = path.join(process.cwd(), "files");
const OUTPUT_IMG_DIR = path.join(process.cwd(), "public", "manual-images");
const OUTPUT_LIB_DIR = path.join(process.cwd(), "lib");

const PDFS = [
  {
    filename: "owner-manual.pdf",
    label: "Owner's Manual",
    prefix: "owner-manual",
  },
  {
    filename: "quick-start-guide.pdf",
    label: "Quick Start Guide",
    prefix: "quick-start",
  },
  {
    filename: "selection-chart.pdf",
    label: "Process Selection Chart",
    prefix: "selection-chart",
  },
];

interface PageImage {
  filename: string;
  url: string;
  source: string;
  page: number;
  label: string;
  type: "diagram" | "text";
}

// Pages with little text are diagrams (wiring, schematics, parts, control
// panels, assembly drawings); text-heavy pages get quoted verbatim instead.
// 700 captures all unambiguous diagrams while excluding spec tables and
// instruction pages that hover around 1000+ chars.
const DIAGRAM_TEXT_THRESHOLD = 700;

async function extractPdf(
  pdfInfo: (typeof PDFS)[0]
): Promise<{ text: string; images: PageImage[] }> {
  const pdfPath = path.join(FILES_DIR, pdfInfo.filename);
  const data = fs.readFileSync(pdfPath);

  // mupdf needs a Buffer/Uint8Array
  const doc = mupdf.Document.openDocument(data, "application/pdf");
  const pageCount = doc.countPages();

  console.log(`  ${pdfInfo.label}: ${pageCount} pages`);

  const allText: string[] = [];
  const images: PageImage[] = [];

  for (let i = 0; i < pageCount; i++) {
    const page = doc.loadPage(i);

    // Extract text
    const structured = page.toStructuredText("preserve-whitespace");
    const pageText = structured.asText();
    allText.push(`--- ${pdfInfo.label} | Page ${i + 1} ---\n${pageText}`);

    // Render page to PNG at 1.5x scale (good quality, reasonable file size)
    const matrix = mupdf.Matrix.scale(1.5, 1.5);
    const pixmap = page.toPixmap(
      matrix,
      mupdf.ColorSpace.DeviceRGB,
      false,
      true
    );
    const png = pixmap.asPNG();

    const imgFilename = `${pdfInfo.prefix}-page-${String(i + 1).padStart(3, "0")}.png`;
    const imgPath = path.join(OUTPUT_IMG_DIR, imgFilename);
    fs.writeFileSync(imgPath, png);

    const dense = pageText.replace(/\s+/g, "").length;
    const type: "diagram" | "text" =
      dense <= DIAGRAM_TEXT_THRESHOLD ? "diagram" : "text";

    images.push({
      filename: imgFilename,
      url: `/manual-images/${imgFilename}`,
      source: pdfInfo.label,
      page: i + 1,
      label: `${pdfInfo.label} — Page ${i + 1}`,
      type,
    });

    process.stdout.write(`\r  Page ${i + 1}/${pageCount} rendered`);
  }

  console.log("");
  return { text: allText.join("\n\n"), images };
}

async function main() {
  console.log("Extracting Vulcan OmniPro 220 manuals...\n");

  fs.mkdirSync(OUTPUT_IMG_DIR, { recursive: true });
  fs.mkdirSync(OUTPUT_LIB_DIR, { recursive: true });

  const allText: string[] = [];
  const allImages: PageImage[] = [];

  for (const pdf of PDFS) {
    console.log(`Processing: ${pdf.label}`);
    const { text, images } = await extractPdf(pdf);
    allText.push(text);
    allImages.push(...images);
  }

  // Write lib/manual-content.ts
  const contentTs = `// Auto-generated by scripts/extract-manual.ts — do not edit manually
export const MANUAL_TEXT = ${JSON.stringify(allText.join("\n\n===\n\n"), null, 0)};
`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-content.ts"), contentTs);
  console.log("\nWrote lib/manual-content.ts");

  // Write lib/manual-images.ts
  const imagesTs = `// Auto-generated by scripts/extract-manual.ts — do not edit manually
export interface ManualImage {
  filename: string;
  url: string;
  source: string;
  page: number;
  label: string;
  type: "diagram" | "text";
}

export const MANUAL_IMAGES: ManualImage[] = ${JSON.stringify(allImages, null, 2)};
`;
  fs.writeFileSync(path.join(OUTPUT_LIB_DIR, "manual-images.ts"), imagesTs);
  console.log("Wrote lib/manual-images.ts");
  console.log(
    `\nDone! Extracted ${allImages.length} page images across ${PDFS.length} PDFs.`
  );
}

main().catch(console.error);
